### PR TITLE
Fixing Content Floating for Vertical Tabs

### LINKED ISSUE #28: Content location in Vertical Tabs
Hello,

Thank you for your effort for delivering foundation 6 for angular.
I noticed that content location in Vertical tabs in "angular-foundation-6" differs from "angular-foundation". Right now it's located below the tabs, but previously it was located right after the tabs (screenshots attached). Is it desired behavior? As for me, such variant of content location is not very useful and it seems like a bug.

Thank you in advance!

foundation5
foundation6

### PR DESCRIPTION
**Pull request by TaysirTayyab**
Fixes #28.

Updates the templates for the tabs directive to use the floating columns classes provided by foundation.

- existing template converted to horizontal layout for tabs
- new template added for vertical layout for tabs using floating columns
  - this is the format [recommended by foundation](https://foundation.zurb.com/sites/docs/tabs.html)
- new tests added to check for floating columns classes on vertical tab configuration

### CODE REVIEW

**Comment by circlingthesun** [comment]
@TaysirTayyab, thanks for the PR. It looks good. You are missing a comma in your test. If you just fix that and please remove the content of the dist folder from your PR I can merge it.

**Comment by TaysirTayyab** [comment]
@circlingthesun requested changes made. Thanks for the sharp eye on catching that!

**Comment by TaysirTayyab** [comment]
More failures ... yay. I'll work on it this week.

**Comment by TaysirTayyab** [comment]
@circlingthesun good to go.

**Comment by circlingthesun** [comment]
Thanks a lot :+1:

**Comment by circlingthesun** [comment]
Actually, it appears that something in your last update slightly broke the previous behaviour. The demo no longer switches to vertical when vertical="true". It instead switches when vertical="vertical" :\

**Comment by TaysirTayyab** [comment]
@circlingthesun my bad on that. I had originally coded it with true/false, but the test setting it up with `vertical='vertical'` (see [here](https://github.com/circlingthesun/angular-foundation-6/pull/35/files#diff-e8d91afd21ae1eb5517a00e846b14347R522)) so I changed it. I'll give you a PR here in a few.

**Comment by TaysirTayyab** [comment]
@circlingthesun #36 added to fix the `vertical='true'` issue.

**Pull request merged**
