### PR TITLE
Changes the order of the browsers in karma in order to fix the failin…

### PR DESCRIPTION
**Pull request by f-anthonioz**
…g test case in

### CODE REVIEW

**Comment by f-anthonioz** [comment]
Hello, I created this pull request because the the test suite is failing on the following test case :

```$modal basic scenarios with default options should destroy modal scope on close FAILED```

I'm really not sure why inverting the browsers fixes the test case, so if you prefer I could actually investigate the root issue instead, let me know plz :)

**Comment by circlingthesun** [comment]
Were your tests fail locally? Because as far as I know the tests are failing on Travis because it's pulling dependencies from GitHub and then gets rate limited.

**Comment by f-anthonioz** [comment]
Yep, just one was failing actually.

For some reason, with the previous browser order, the modal scope didn't get destroyed, I digged for 10 minutes but didn't find anything conclusive.

**Comment by circlingthesun** [comment]
:+1:

**Pull request merged**
