### PR TITLE
Adds the navigation arrows to Orbit slider

### PR DESCRIPTION
**Pull request by f-anthonioz**
I created this pull request to add control arrow to Orbit slider, I'm not entirely sure, what more you need here, so let me know if I can complement in any way.

PS: I haven't added any specs for this as the whole orbit module is untested at the moment.

### CODE REVIEW

**Comment by circlingthesun** [comment]
I'll have a look at this a little later today. Please ping me if I forget. Also, could you exclude the build artefacts from PRs in the future? It makes the diff less busy and easier to review.

**Comment by f-anthonioz** [comment]
Took the build artifacts out of the commit. Thanks for your reactivity :)

**Comment by circlingthesun** [comment]
Published as v0.11.17 👍

**Comment by f-anthonioz** [comment]
Great ! Thank you very much !

**Pull request merged**
