### PR TITLE
Autofocus the modal dialog

### PR DESCRIPTION
**Pull request by onizet**
Hey,

I propose you to automatically focus the first control with autofocus attribute or fallback to dialog itself.
In any case, when a modal form opens, I want to give it the focus otherwise tabbing will cycle through the back window.

### CODE REVIEW

**Comment by circlingthesun** [comment]
Hey, thanks for the PR. The focus will have to happen after the modal has opened. Focusing inputs before animations have completed will result in the the window scrolling up to an intermediate position. You should be able to use the promise returned at the end of the open function.

**Comment by onizet** [comment]
You know your job ;-)
I've just updated my commit to use a promise. Thank you !

**Comment by circlingthesun** [comment]
I'm heading out for a bit. Hope to merge this when I get back.

**Comment by onizet** [comment]
I still have a lot to learn again... thanks for your feedback

**Comment by circlingthesun** [comment]
Thanks for your contribution :+1:

**Pull request merged**
