### PR TITLE
Add events to accordions and tabs

### PR DESCRIPTION
**Pull request by kball**
Add events to accordions and tabs, allowing us to listen in/hook in to when events happen.  Naming convention roughly follows the event naming from Foundation for Sites.

### CODE REVIEW

**Comment by circlingthesun** [comment]
Sorry for the delayed response, I'm currently abroad. This looks good. I'm wondering if 'zf' is the right namespace to use. Perhaps it's better to use a unique prefix such as 'af'? Thoughts?

**Comment by kball** [comment]
`af` seems reasonable to me. I'll revise and push up the update tomorrow.

**Comment by kball** [comment]
@circlingthesun updated event namespace to af

**Comment by kball** [comment]
ping

**Comment by circlingthesun** [comment]
Thanks for the PR and sorry for the wait. This has been released as v0.10.13.

**Pull request merged**
